theme: minima
repository: nineties/manifold-optimization

title: Manifold Optimization
author:
    name: 中村晃一(Koichi Nakamura)
    email: koichi@idein.jp

github:
    - project_tagline: test
    - is_user_page: true
    - is_project_page: false

google_analytics: UA-129434657-1
