baseURL = "https://nineties.github.io/manifold-optimization/"
languageCode = "ja-jp"
title = "Manifold Optimization"
theme = "hugo-theme-basic"
publishDir = "docs"

[params]
customCSS = ["static/custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
changefreq = 'monthly'
filename = 'sitemap.xml'
priority = 0.5
